export ZSH=~/.config/oh-my-zsh
export EDITOR='vim -w'
export FUZZY=$HOME/.bin/fuzzy/
export NAS=$HOME/Drive

PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/bin/usr/sbin:~/.bin:~/.binaries
