# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.dotfiles/zsh/zshenv
source ~/.dotfiles/zsh/zshAlias
source ~/.dotfiles/zsh/zshAliasPrivate

zstyle ':completion::complete:*' use-cache 1
zstyle ":conda_zsh_completion:*" use-groups true

# Path to your oh-my-zsh installation.
TERM=xterm-256color #fixes weird bug in python shell
zmodload zsh/zprof

ZSH_THEME="powerlevel10k"
#ZSH_THEME="agkozak"


# CASE_SENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd/mm/yyyy"

GTK_THEME=Adwaita:dark

#zstyle ':completion:*' menu select
#Plugins
plugins=(
  #chucknorris
  colorize
  z
  zsh-navigation-tools
  vi-mode
  auto-ls
  colored-man-pages
  zsh-autopair
  sudo #double-escape puts "sudo" before last command
  zsh-autosuggestions #suggest. based on history
  #zsh-syntax-highlighting
)

AUTO_LS_COMMANDS=(ls)

source $ZSH/plugins/z/z.sh   #jump around with z FIND
source $ZSH/oh-my-zsh.sh

alias ls='exa --icons'

source /opt/ros/noetic/setup.zsh

bindkey '^ ' autosuggest-accept  #for zsh-autosuggestions

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$($HOME'/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

source /home/len/.config/broot/launcher/bash/br
